/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.kentama7.mapstruct.sample

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
